# -*- coding: utf-8 -*-
"""Mapa_Colombia.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/15MrWiIfHuHcQnfMfH6cf6BzAJtiGWKUi
## Importar librerias
"""

import pandas as pd
#import numpy as np
import plotly.graph_objs as go
import plotly.offline as pyo # para exportar en html
import json
import plotly.express as px
#from urllib.request import urlopen
import dash_bootstrap_components as dbc

"""## Importar json con las ubicaciones por departamento"""
ruta_archivo = "D:/UNIANDES/ACTD/Git/Repositorio3/ACTD_Proyecto_3/data.json"

#with urlopen('https://gist.githubusercontent.com/A4lfr32/6005403aa6a2e1ddb51ef53860939f23/raw/22a23f5e10d698306c14c6ceddf9ef35df2a665c/MunicipiosVeredas1MB.json') as response:
#    counties = json.load(response)

with open(ruta_archivo, encoding="utf8") as response:
    counties = json.load(response)

#counties

df = pd.read_excel('D:/UNIANDES/ACTD/Git/Repositorio3/ACTD_Proyecto_3/datos6.xlsx',dtype={"cole_cod_mcpio_ubicacion": str,"cole_cod_mcpio_ubicacion":str})

df= df.astype("string")
#print(df.head(10))
#print(df.dtypes)
#print(len(df))
"""## Crear mapa"""
#locs = ['BARRANQUILLA','BARANOA']
locs = df['cole_mcpio_ubicacion']

#for loc in counties['features']:
#    loc['id'] = loc['properties']['MPIO_CNMBR']

loc_2=[]
x=0
dfPrueba=df[["avg_value"]]
dfPrueba["DPTOMPIO"]=df["cole_cod_mcpio_ubicacion"]
#print(dfPrueba.dtypes)

"""for loc in counties['features']:
    print(loc)
    x+=1
    if(x==4):
        break

print(loc_2)"""
dfUltimo = dfPrueba.iloc[:19]
print(dfUltimo)


   
fig = px.choropleth(dfUltimo,
                    geojson=counties,
                    locations="DPTOMPIO",
                    #mapbox_style="carto-positron",
                    color="avg_value",
                    range_color=(0, 12),
                    color_continuous_scale='Viridis')
#colorbar_title="Promedio Agregado")
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0},
                        mapbox_zoom=3.4,
                        mapbox_center = {"lat": 4.570868, "lon": -74.2973328})
fig.show()


